fix: build on windows

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -166,6 +166,52 @@ jobs:
             cargo run --example "$(basename "${example%.rs}")" ${{ env.CARGO_FEATURES }} --features="$(cat ${example%.rs}-features)"
           done
 
+  cargo-build-windows:
+    name: Cargo build Windows
+    runs-on: windows-latest
+    needs:
+      - changes
+    if: |
+      github.event_name == 'pull_request' &&
+      fromJSON(needs.changes.outputs.rust) == true
+    steps:
+      - &disable_autocrlf
+        name: Disable autocrlf
+        shell: pwsh
+        run: |
+          git config --global core.autocrlf false
+          git config --global core.eol lf
+
+      - *checkout
+
+      - *cache_cargo
+
+      - *set_up_mold
+
+      - &set_up_toolchain_windows
+        name: Set up toolchain
+        shell: pwsh
+        run: |
+          Remove-Item -ErrorAction SilentlyContinue ${HOME}/.cargo/bin/cargo-fmt.exe
+          Remove-Item -ErrorAction SilentlyContinue ${HOME}/.cargo/bin/rust-analyzer.exe
+          Remove-Item -ErrorAction SilentlyContinue ${HOME}/.cargo/bin/rustfmt.exe
+
+          rustup self update
+          rustup update
+          rustup show active-toolchain || rustup toolchain install
+          rustup show
+
+          cargo --version
+
+      - *cache_target
+
+      - *set_up_sccache
+
+      - name: Build
+        shell: pwsh
+        run: |
+          cargo build --all-features --all-targets --locked --workspace --verbose
+
   cargo-fmt:
     name: Cargo fmt
     runs-on: ubuntu-latest
@@ -287,7 +333,7 @@ jobs:
           disable_telem: true
           env_vars: OS,RUST
           fail_ci_if_error: true
-          # flags: tests
+          flags: linux
           files: reports/lcov
           name: code-coverage
           plugins: ""
@@ -301,7 +347,7 @@ jobs:
           disable_telem: true
           env_vars: OS,RUST
           fail_ci_if_error: true
-          # flags: tests
+          flags: linux
           files: reports/results.xml
           name: test-results
           plugins: ""
@@ -310,6 +356,128 @@ jobs:
 
       - name: Fail if tests failed
         shell: bash
+        if: |
+          steps.tests.outcome != 'success'
+        run: |
+          # the test reporter we use (or any for that matter)
+          # all show a report. But we cannot depend on that report because
+          # we don't know which subsection it belongs in GitHub
+          # so we explicitly fail this one
+          # which will fail All Done
+          exit 1
+
+  cargo-test-and-report-windows:
+    name: Cargo test (and report) Windows
+    runs-on: windows-latest
+    permissions:
+      checks: write
+      id-token: write
+      pull-requests: write
+    steps:
+      - *disable_autocrlf
+
+      - *checkout
+
+      - *cache_cargo
+
+      - *set_up_mold
+
+      - *set_up_toolchain_windows
+
+      - *cache_target
+
+      - *set_up_sccache
+
+      - name: Install llvm-tools
+        shell: pwsh
+        run: |
+          rustup component add llvm-tools
+
+          # restore symlinks
+          rustup update
+
+      - name: Install nextest, custom test runner, with native support for junit and grcov
+        uses: taiki-e/install-action@a2352fc6ce487f030a3aa709482d57823eadfb37 # v2.75.16
+        with:
+          tool: cargo-nextest, grcov
+
+      - name: Build with instrumentation support
+        shell: pwsh
+        env:
+          RUSTFLAGS: "${{ env.RUSTFLAGS }} --allow=warnings -Cinstrument-coverage"
+          # build-* ones are not parsed by grcov
+          LLVM_PROFILE_FILE: "profiling/build-%p-%m.profraw"
+        run: |
+          cargo build --all-features --all-targets --locked --workspace --verbose
+
+      - name: Run nextest
+        shell: pwsh
+        id: tests
+        env:
+          RUSTFLAGS: "${{ env.RUSTFLAGS }} --allow=warnings -Cinstrument-coverage"
+          LLVM_PROFILE_FILE: "profiling/profile-%p-%m.profraw"
+        run: |
+          cargo nextest run --profile ci --no-fail-fast --all-targets --all-features --workspace
+        continue-on-error: true
+
+      - name: Upload test results
+        uses: EnricoMi/publish-unit-test-result-action/windows@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
+        with:
+          check_name: Test results Windows
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          files: |
+            reports/results.xml
+
+      - name: Run grcov
+        shell: pwsh
+        run: |
+          grcov $(Get-ChildItem -Recurse -Filter '*.profraw' -Path . | % { $_.FullName }) `
+            --binary-path ./target/debug/ `
+            --branch `
+            --ignore-not-existing `
+            --keep-only "src/**" `
+            --llvm `
+            --output-path ./reports/lcov.info `
+            --output-type lcov `
+            --source-dir .
+
+      - name: Record Rust version
+        shell: pwsh
+        run: |
+          $version=(rustc --version)
+
+          Add-Content -Path "$env:GITHUB_ENV" -Value "RUST=$version"
+
+      - name: Upload coverage results (to Codecov.io)
+        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
+        with:
+          disable_search: true
+          disable_telem: true
+          env_vars: OS,RUST
+          fail_ci_if_error: true
+          flags: windows
+          files: reports/lcov.info
+          name: code-coverage
+          plugins: ""
+          report_type: "coverage"
+          use_oidc: true
+
+      - name: Upload test results (to Codecov.io)
+        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
+        with:
+          disable_search: true
+          disable_telem: true
+          env_vars: OS,RUST
+          fail_ci_if_error: true
+          flags: windows
+          files: reports/results.xml
+          name: test-results
+          plugins: ""
+          report_type: "test_results"
+          use_oidc: true
+
+      - name: Fail if tests failed
+        shell: pwsh
         if: |
           steps.tests.outcome != 'success'
         run: |
@@ -346,6 +514,34 @@ jobs:
         uses: actions-rs-plus/clippy-check@23b52efac3da0e2b197a9ad2e7be0f515502aaaf # v2.5.0
         with:
           args: ${{ env.CARGO_FEATURES }} --all-targets --frozen --workspace
+
+  cargo-clippy-and-report-windows:
+    name: Cargo clippy (and report) Windows
+    runs-on: windows-latest
+    needs:
+      - changes
+    if: |
+      github.event_name == 'pull_request' &&
+      fromJSON(needs.changes.outputs.rust) == true
+    steps:
+      - *disable_autocrlf
+
+      - *checkout
+
+      - *cache_cargo
+
+      - *set_up_mold
+
+      - *set_up_toolchain_windows
+
+      - *cache_target
+
+      - *set_up_sccache
+
+      - name: Run Clippy for GitHub Actions report
+        uses: actions-rs-plus/clippy-check@23b52efac3da0e2b197a9ad2e7be0f515502aaaf # v2.5.0
+        with:
+          args: --all-features --all-targets --locked --workspace --verbose
 
   cargo-msrv:
     name: Cargo MSRV
@@ -425,12 +621,15 @@ jobs:
     needs:
       - changes
       - cargo-build
+      - cargo-build-windows
       - cargo-clippy-and-report
+      - cargo-clippy-and-report-windows
       - cargo-docs
       - cargo-examples
       - cargo-fmt
       - cargo-msrv
       - cargo-test-and-report
+      - cargo-test-and-report-windows
     if: |
       !cancelled()
     steps:
